name: medici
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  sqflite: ^2.3.3+2
  sqflite_common_ffi: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/icons/
    - images/

  fonts:
     - family: Montserrat
       fonts:
         - asset: fonts/Montserrat-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#F2F1E9"
  image: images/splash.png

  android_12:
    image: images/splash.png
    icon_background_color: "#F2F1E9"

  web: false
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: false
  image_path_ios: "images/logo_ios.png"
  background_color_ios: "#FFFFFF"
  image_path: "images/logo_android.png"
  adptative_icon_background: "#FFFFFF"
  adptative_icon_foreground: "images/splash.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false